nome: Construir

ligado:
  empurre:
    ramificações:
      ¿ ¿ - principais


trabalhos:
  construir:
    nome: Construir e, e analisar
    runs-on: ubuntu-último
    
    passos:
      ¿ ¿ - usos: ações/checkout@v4
        com:
          busca-profundidade: 0  # Clones rasos devem ser desativados para uma melhor relevância da análise
      ¿ ¿ - usos: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_ TOKEN: ${{ segredos.SONAR_ TOKEN }}
          SONAR_ HOST_URL: ${{ segredos.SONAR_HOST_URL }}
      # Se você deseja falhar em seu trabalho quando o Portão da Qualidade estiver vermelho, descomente o
      # seguindo linhas. Isso normalmente seria usado para falhar uma implantação.
      # - usa: SonarSource/sonarqube-quality-gate-action@v1
      # timeout-minutos: 5
      # env:
      #SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
